### ISSUE TITLE
Empty toolbar if you click immediately after adding the plugin table

### ISSUE THREAD

**Issue by artemshar** [4rw44z/editorjs-table#3]
Hi! Thanks for your plugin! So far, this is the best plugin for Editor.js I've seen!

I found one small UX bug only with this plugin.

If next action after adding the plugin will be click on the toolbar option, toolbar will be empty.

![image](https://user-images.githubusercontent.com/52139984/103218985-5668b700-48d1-11eb-8d22-5ffdac808d66.png)

**Comment by arwazjamal** [comment]
Fixed in latest Release 1.4.9
